//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angnetcommerce
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AaauctionEntities : DbContext
    {
        public AaauctionEntities()
            : base("name=AaauctionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<address> addresses { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<features_on_vehicles_for_sale> features_on_vehicles_for_sale { get; set; }
        public DbSet<make> makes { get; set; }
        public DbSet<model> models { get; set; }
        public DbSet<vehicle_category> vehicle_category { get; set; }
        public DbSet<vehicle_features> vehicle_features { get; set; }
        public DbSet<vehicle_for_sale> vehicle_for_sale { get; set; }
        public DbSet<vehicle_order> vehicle_order { get; set; }
    }
}
