//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angnetcommerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int customerid { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> mobile { get; set; }
        public Nullable<int> phone { get; set; }
    }
}
