//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angnetcommerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class images_on_vehicles_for_sale
    {
        public int imageid { get; set; }
        public string imageurl { get; set; }
        public int stock_no { get; set; }
    }
}
