//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angnetcommerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class model
    {
        public int id { get; set; }
        public string model_name { get; set; }
        public int make_id { get; set; }
    }
}
