//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angnetcommerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle_order
    {
        public int orderid { get; set; }
        public int stock_no { get; set; }
        public int customerid { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<bool> ispaid { get; set; }
        public string payment_details { get; set; }
    }
}
