//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angnetcommerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle_for_sale
    {
        public int stock_no { get; set; }
        public int model_id { get; set; }
        public int vehicle_category_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> year { get; set; }
        public string month { get; set; }
        public string chassis_no_1 { get; set; }
        public string chassis_no_2 { get; set; }
        public string grade { get; set; }
        public string ETD { get; set; }
        public string color { get; set; }
        public Nullable<int> KM_ran { get; set; }
        public string uel { get; set; }
        public Nullable<bool> gear_at { get; set; }
        public Nullable<int> CC { get; set; }
        public Nullable<int> no_of_doors { get; set; }
        public Nullable<System.DateTime> last_modified_date { get; set; }
    }
}
